### ISSUE TITLE
Проверка работы spaceless и поведения {%- ... -%}

### ISSUE THREAD

**Issue by qantus** [studio107/Mindy_Template#7]
https://github.com/studio107/Meta/blob/master/templates/meta/meta_helper.html

Не смог добиться того, чтобы тайтл выводился в одну строку, но код был читабелен. 

PS: может просто я упорот)

**Comment by max107** [comment]
https://github.com/studio107/Mindy_Template/commit/5a184a2c502118f9c677654e172dac4bace4833d
